apiVersion: v1
kind: Pod
metadata:
  name: wechat-service-thisisatest
  namespace: kube-test
  labels:
    app: wechat-service
spec:
  containers:
    - name: wechat-service
      image: 192.168.1.104:5000/septemberhx/wechat-service:v1.0
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: /var/log/mclient
          name: log-volume
      env:
        - name: MCLUSTER_IP
          value: "192.168.1.104"
        - name: MCLUSTER_PORT
          value: "30761"
  volumes:
    - name: log-volume
      hostPath:
        path: /data/hexiang/test-dir/log
